# Python Review 

Short review about some core concepts in Python exemplified by objects in the Numpy Library

- recall basic vocab 
- practice markdown syntax 

## Libraries and packages

**Library** is a colleciton of code that we can use to preform specific tasks in our programs. It can be a single file or multiple files.

**NumPy:**

- core library for numerical computing in python
- many of libraries us NumPy arrays as their building blocks 
- computations on NumPy are optimized 



In [1]:
import numpy as np

## Variables 

**variables** a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to a variable a 
a = np.array( [[1,1,2], [3,5,8]] )

To view a variable's value from our Jupyter notebook

In [3]:
# run the cell
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
print(a)

[[1 1 2]
 [3 5 8]]


## Convention: use 'snack_case' for naming variables

Thisn is the convention we will use in the course. Why? 'my-variable' or 'MyVariable' or 'myVariable'
PEP 8 - Style guide for Python Code recommends snake_case

**Remember that variable names should be both be descriptive and consise!**

## Objects 

**obeject** is a bundle of *properties* and *actions* about something specific. 

Example:

object: data frame 
properties: number of rows and columns and date created 
actions: selecting a specific row or adding a new column 

A variable is the name we give a specific object, and the same object can be referenced by different variables. 

in practice, we can often use the word variable and object interchangeably.

## Types 

Eevry object in Python has a **type** 


The numpy.ndarray is the core object/data type in the NumPy
package. We can check the type of an entry in the array by indexing:

In [5]:
print(a[0,0])

1


In [6]:
type(a[0,0])


numpy.int64

## Notice the type of the value 1 in the array is numpy.int64 and not just the standard Python integer type int. The NumPy type numpy.int64 is telling us 1 is an integer stored as a 64-bit number. NumPy has its own data types to deal with numbers depending on memory storage and floating point precision, click here to know see all the types.

print was our first example of a Python function. Functions take in a set of arguments, separated by commas, and use those arguments to create an output. There are several built-in funcions in Python, most of them are for interacting with the Python basic data types such as int (integers), float (decimal numbers), str (strings), and bool (boolean values).

In [7]:
?print 

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


What we get is a doctring. Functions have two types of arguments 

- **non-optional arguments**: arguments you need to specify for the function to do something, and

- **optional arguments:** arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form optional_argument = default_value.

Example

'end' is a parameter in 'print' with default value a new line
We can pass the value ':-)' to this parameter so that it finishes the line with ':-)'

print('chnage the end parameter', end= ':-)
')

## Attributes and methods 

An object in Python has attributes and methods. 
- An **attribute** is a property of the object, some piece of information about it. 
- A **method** is a procedure associated with an object, so it is an action where the main ingredient is the object

Example: 
 
NumPy arrays have many mehtods and attributes. For example:

In [8]:
a

array([[1, 1, 2],
       [3, 5, 8]])

In [9]:
# T is example of an  attribute. it returns the transpose of the array 
print(a.T)

[[1 3]
 [1 5]
 [2 8]]


In [10]:
print(type(a))

<class 'numpy.ndarray'>


In [12]:
print(a.shape)

(2, 3)


In [14]:
print('dim:', a.ndim, '| type', type(a.ndim))

dim: 2 | type <class 'int'>


Attributes can have many different data types 

Some examples of methods 

In [16]:
print(a)
a.min(axis=0)

[[1 1 2]
 [3 5 8]]


array([1, 1, 2])

mehtods are functions associated with an object. We can confirm this!

In [18]:
a.tolist()

[[1, 1, 2], [3, 5, 8]]

In [21]:
# Exercise: 

?print


Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [24]:
## create to vairables, one number 77 and one string 99

num = 77
string_99 = '99'

In [25]:
num
string_99

'99'

In [27]:
print(num, string_99, num, sep='%')

77%99%77
